services:
  database:
    image: mysql
    container_name: request-api
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'api'
    ports:
      - '3306:3306'
